In [ ]:
import numpy as np

X = np.array(([1,2],
              [2,3],
              [3,4],
              [4,5],
              [5,6]))

y = np.array(([1, 1, 0, 0, 0]))

In [ ]:
def EuclideanDistance(x1, x2):
    ED = np.sqrt(np.sum((x1 - x2)**2))
    return ED

class KNN:
    def __init__(self, k=3):
        self.k = k

    def fit(self, X, y):
        self.X = X
        self.y = y

    def predict(self, X):
        predictions = []
        for x in X:
            prediction = self._predict(x)
            predictions.append(prediction)
        return predictions

    def _predict(self, x):
        distances = []
        for x_row in self.X:
            distance = EuclideanDistance(x_row, x)
            distances.append(distance)
        indices = np.argsort(distances)
        indices = indices[:self.k]
        label = self.Most_Common_Label(y[indices])
        return np.int64(label)

    def Most_Common_Label(self, y):
        labels, counts = np.unique(y, return_counts=True)
        index = np.argmax(counts)
        return labels[index]

def accuracy(y_test, y_pred):
    accuracy = np.sum(y_test == y_pred) / len(y_test)
    return accuracy


model = KNN(k=5)
model.fit(X, y)
predictions = model.predict(X)
print(predictions)
print(y)

accuracy = accuracy(y, predictions)
print(accuracy)

[array(0), array(0), array(0), array(0), array(0)]
[1 1 0 0 0]
0.6


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

model = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
model.fit(X, y)
predictions = model.predict(X)
print(predictions)
print(y)

accuracy = accuracy_score(y, predictions)
print(accuracy)

[0 0 0 0 0]
[1 1 0 0 0]
0.6
