In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [ ]:
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]).reshape(-1, 1)
print(X)


[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [ ]:
bias_column = np.ones((X.shape[0], 1))
X_with_bias = np.hstack((bias_column, X))

print (X_with_bias)

[[ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 1.  8.]
 [ 1.  9.]
 [ 1. 10.]]


In [ ]:
X_df = pd.DataFrame(X_with_bias, columns=['Bias', 'Feature'])

print (X_df)

   Bias  Feature
0   1.0      1.0
1   1.0      2.0
2   1.0      3.0
3   1.0      4.0
4   1.0      5.0
5   1.0      6.0
6   1.0      7.0
7   1.0      8.0
8   1.0      9.0
9   1.0     10.0


In [ ]:
#true_weight = np.array([10, 42])
y = np.array([0,0,0,0,1,1,1,1,1,1])

print (y)

[0 0 0 0 1 1 1 1 1 1]


In [ ]:
y_df = pd.DataFrame(y, columns=['Target'])

print (y_df)

   Target
0       0
1       0
2       0
3       0
4       1
5       1
6       1
7       1
8       1
9       1


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size=0.2, random_state=42)

print (X_train)
print (y_train)
print (X_test)
print (y_test)

   Bias  Feature
5   1.0      6.0
0   1.0      1.0
7   1.0      8.0
2   1.0      3.0
9   1.0     10.0
4   1.0      5.0
3   1.0      4.0
6   1.0      7.0
   Target
5       1
0       0
7       1
2       0
9       1
4       1
3       0
6       1
   Bias  Feature
8   1.0      9.0
1   1.0      2.0
   Target
8       1
1       0


In [ ]:
num_samples, num_features = X_train.shape

np.random.seed(42)
weights = np.random.rand(num_features, 1)

print("Shape of weight matrix:", weights.shape)
print("Weight matrix:\n", weights)

Shape of weight matrix: (2, 1)
Weight matrix:
 [[0.37454012]
 [0.95071431]]


In [ ]:
y_pred = np.dot(X_train, weights)
print (y_pred)

[[6.07882596]
 [1.32525443]
 [7.98025457]
 [3.22668304]
 [9.88168318]
 [5.12811165]
 [4.17739734]
 [7.02954026]]


In [ ]:
m = num_samples
dw = (1/m) * np.dot(X_train.T, (y_pred - y_train))
print (dw)

[[ 4.9784688 ]
 [33.21175714]]


In [ ]:
weights = weights - 0.01 * dw
print (weights)

[[0.32475543]
 [0.61859673]]


In [ ]:
n_iters = 1000
for i in range(n_iters):
    y_pred = np.dot(X_train, weights)
    dw = (1/m) * np.dot(X_train.T, (y_pred - y_train))
    weights = weights - 0.01 * dw
    print (weights)

[[0.29373506]
 [0.41376141]]
[[0.27429083]
 [0.28744545]]
[[0.26198842]
 [0.20956741]]
[[0.25409233]
 [0.16157027]]
[[0.24891504]
 [0.13200634]]
[[0.24541554]
 [0.11381364]]
[[0.24295164]
 [0.10263567]]
[[0.24112716]
 [0.09578495]]
[[0.23969771]
 [0.0916036 ]]
[[0.23851254]
 [0.08906888]]
[[0.23747862]
 [0.08754986]]
[[0.2365386 ]
 [0.08665734]]
[[0.23565706]
 [0.08615121]]
[[0.23481217]
 [0.08588337]]
[[0.23399046]
 [0.08576244]]
[[0.23318362]
 [0.08573205]]
[[0.23238652]
 [0.08575743]]
[[0.231596  ]
 [0.08581714]]
[[0.2308101 ]
 [0.08589793]]
[[0.23002761]
 [0.08599165]]
[[0.22924779]
 [0.08609326]]
[[0.22847019]
 [0.08619966]]
[[0.2276945 ]
 [0.08630893]]
[[0.22692057]
 [0.08641988]]
[[0.22614827]
 [0.0865318 ]]
[[0.22537754]
 [0.08664422]]
[[0.22460833]
 [0.08675687]]
[[0.22384062]
 [0.08686959]]
[[0.22307438]
 [0.08698226]]
[[0.22230962]
 [0.08709482]]
[[0.22154631]
 [0.08720723]]
[[0.22078444]
 [0.08731947]]
[[0.22002403]
 [0.08743153]]
[[0.21926505]
 [0.08754338]]
[[0.21850752]


In [ ]:
def predict (X, weights):
    y_pred = np.dot(X, weights)
    return y_pred

y_pred = predict (X_test, weights)
print (y_pred)
print (y_test)


[[1.11694879]
 [0.15735962]]
   Target
8       1
1       0


In [ ]:
class LogisticRegression:
  def __init__(self, num_features):
    self.lr = 0.001
    self.np_iter = 1000
    self.weights = np.random.rand(num_features, 1)

  def fit(self, X_train, y_train):
    num_samples, num_features = X_train.shape
    y_train_np = y_train.values
    for i in range(self.np_iter):
      y_pred = np.dot(X_train, self.weights)
      y_pred = self.sigmoid(y_pred)
      dw = (1/num_samples) * np.dot(X_train.T, (y_pred - y_train_np))
      self.weights = self.weights - self.lr * dw

  def predict(self , X):
    y_pred = np.dot(X, self.weights)
    y_pred = self.sigmoid(y_pred)
    return y_pred

  def sigmoid(self, z):
    z = np.exp(-z)
    z = np.add(1, z)
    z = np.divide(1, z)
    z = np.where(z >= 0.5, 1, 0)
    return z

In [ ]:
model = LogisticRegression(num_features)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print (y_pred)
print (y_test)

[[1]
 [1]]
   Target
8       1
1       0
