In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [ ]:
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]).reshape(-1, 1)
print(X)


[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [ ]:
bias_column = np.ones((X.shape[0], 1))
X_with_bias = np.hstack((bias_column, X))

print (X_with_bias)

[[ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 1.  8.]
 [ 1.  9.]
 [ 1. 10.]]


In [ ]:
X_df = pd.DataFrame(X_with_bias, columns=['Bias', 'Feature'])

print (X_df)

   Bias  Feature
0   1.0      1.0
1   1.0      2.0
2   1.0      3.0
3   1.0      4.0
4   1.0      5.0
5   1.0      6.0
6   1.0      7.0
7   1.0      8.0
8   1.0      9.0
9   1.0     10.0


In [ ]:
true_weight = np.array([10, 42])
y = np.array([3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print (y)

[ 3  4  5  6  7  8  9 10 11 12]


In [ ]:
y_df = pd.DataFrame(y, columns=['Target'])

print (y_df)

   Target
0       3
1       4
2       5
3       6
4       7
5       8
6       9
7      10
8      11
9      12


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size=0.2, random_state=42)

print (X_train)
print (y_train)
print (X_test)
print (y_test)

   Bias  Feature
5   1.0      6.0
0   1.0      1.0
7   1.0      8.0
2   1.0      3.0
9   1.0     10.0
4   1.0      5.0
3   1.0      4.0
6   1.0      7.0
   Target
5       8
0       3
7      10
2       5
9      12
4       7
3       6
6       9
   Bias  Feature
8   1.0      9.0
1   1.0      2.0
   Target
8      11
1       4


In [ ]:
num_samples, num_features = X_train.shape

np.random.seed(42)
weights = np.random.rand(num_features, 1)

print("Shape of weight matrix:", weights.shape)
print("Weight matrix:\n", weights)

Shape of weight matrix: (2, 1)
Weight matrix:
 [[0.37454012]
 [0.95071431]]


In [ ]:
y_pred = np.dot(X_train, weights)
print (y_pred)

[[6.07882596]
 [1.32525443]
 [7.98025457]
 [3.22668304]
 [9.88168318]
 [5.12811165]
 [4.17739734]
 [7.02954026]]


In [ ]:
m = num_samples
dw = (1/m) * np.dot(X_train.T, (y_pred - y_train))
print (dw)

[[ -1.8965312 ]
 [-10.78824286]]


In [ ]:
weights = weights - 0.01 * dw
print (weights)

[[0.39350543]
 [1.05859673]]


In [ ]:
n_iters = 1000
for i in range(n_iters):
    y_pred = np.dot(X_train, weights)
    dw = (1/m) * np.dot(X_train.T, (y_pred - y_train))
    weights = weights - 0.01 * dw
    print (weights)

[[0.40634756]
 [1.12498016]]
[[0.41541017]
 [1.16576348]]
[[0.42213908]
 [1.19075462]]
[[0.42742618]
 [1.20600399]]
[[0.4318217 ]
 [1.21524405]]
[[0.43566506]
 [1.22077734]]
[[0.43916566]
 [1.22402426]]
[[0.44245267]
 [1.22586105]]
[[0.44560578]
 [1.22682826]]
[[0.44867417]
 [1.22725934]]
[[0.45168817]
 [1.22736001]]
[[0.45466648]
 [1.22725716]]
[[0.45762067]
 [1.22702907]]
[[0.46055787]
 [1.22672403]]
[[0.46348247]
 [1.22637184]]
[[0.46639719]
 [1.22599086]]
[[0.46930372]
 [1.22559244]]
[[0.4722031 ]
 [1.22518357]]
[[0.47509597]
 [1.22476856]]
[[0.47798274]
 [1.22435007]]
[[0.48086366]
 [1.22392974]]
[[0.48373889]
 [1.22350859]]
[[0.48660853]
 [1.22308723]]
[[0.48947265]
 [1.22266605]]
[[0.49233129]
 [1.22224529]]
[[0.49518448]
 [1.22182508]]
[[0.49803226]
 [1.22140553]]
[[0.50087463]
 [1.22098668]]
[[0.50371162]
 [1.22056857]]
[[0.50654323]
 [1.22015122]]
[[0.50936948]
 [1.21973463]]
[[0.51219038]
 [1.21931882]]
[[0.51500594]
 [1.21890379]]
[[0.51781617]
 [1.21848954]]
[[0.52062109]


In [ ]:
def predict (X, weights):
    y_pred = np.dot(X, weights)
    return y_pred

y_pred = predict (X_test, weights)
print (y_pred)
print (y_test)


[[11.07769068]
 [ 3.83230288]]
   Target
8      11
1       4


In [ ]:
class LinearRegression:
  def __init__(self, num_features):
    self.lr = 0.001
    self.np_iter = 1000
    self.weights = np.random.rand(num_features, 1)

  def fit(self, X_train, y_train):
    num_samples, num_features = X_train.shape
    y_train_np = y_train.values
    for i in range(self.np_iter):
      y_pred = np.dot(X_train, self.weights)
      dw = (1/num_samples) * np.dot(X_train.T, (y_pred - y_train_np))
      self.weights = self.weights - self.lr * dw

  def predict(self , X):
    y_pred = np.dot(X, self.weights)
    return y_pred

In [ ]:
model = LinearRegression(num_features)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print (y_pred)
print (y_test)

[[11.5226064]
 [ 2.8719421]]
   Target
8      11
1       4
