In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

X =  np.array([1,2,3,4,5,6,7,8,9,10])

bias_column = np.ones((X.shape[0],1))
X_with_bias = np.column_stack((bias_column,X))
print (X_with_bias)

[[ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 1.  8.]
 [ 1.  9.]
 [ 1. 10.]]


In [2]:
X_df = pd.DataFrame(X_with_bias, columns=['Bias', 'Feature'])

print (X_df)

   Bias  Feature
0   1.0      1.0
1   1.0      2.0
2   1.0      3.0
3   1.0      4.0
4   1.0      5.0
5   1.0      6.0
6   1.0      7.0
7   1.0      8.0
8   1.0      9.0
9   1.0     10.0


In [3]:
y = np.array([0,0,0,0,1,1,1,1,1,1])

y_df = pd.DataFrame(y, columns=['Target'])

print (y_df)

   Target
0       0
1       0
2       0
3       0
4       1
5       1
6       1
7       1
8       1
9       1


In [4]:
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size=0.2, random_state=42)

print (X_train)
print (y_train)
print (X_test)
print (y_test)

   Bias  Feature
5   1.0      6.0
0   1.0      1.0
7   1.0      8.0
2   1.0      3.0
9   1.0     10.0
4   1.0      5.0
3   1.0      4.0
6   1.0      7.0
   Target
5       1
0       0
7       1
2       0
9       1
4       1
3       0
6       1
   Bias  Feature
8   1.0      9.0
1   1.0      2.0
   Target
8       1
1       0


In [5]:
num_samples, num_features = X_train.shape

np.random.seed(42)
weights = np.random.rand(num_features, 1)

print("Shape of weight matrix:", weights.shape)
print("Weight matrix:\n", weights)

Shape of weight matrix: (2, 1)
Weight matrix:
 [[0.37454012]
 [0.95071431]]


In [17]:
def sigmoid(z):
  z = np.exp(-z)
  z = np.add(1, z)
  z = np.divide(1, z)
  z = np.where(z >= 0.5, 1, 0)
  return z

clf = sigmoid(0)
print(clf)

1


In [24]:
y_pred = np.dot(X_df, weights)
print(y_pred)
print(sigmoid(y_pred))

[[1.32525443]
 [2.27596873]
 [3.22668304]
 [4.17739734]
 [5.12811165]
 [6.07882596]
 [7.02954026]
 [7.98025457]
 [8.93096888]
 [9.88168318]]
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [28]:
m = num_samples
y_train_np = y_train.to_numpy()
y_pred_train = np.dot(X_train, weights)
y_pred_train = sigmoid(y_pred_train)
dw = (1/num_samples) * np.dot(X_train.T, (y_pred_train - y_train_np))
print(dw)

[[0.375]
 [1.   ]]


In [29]:
learning_rate = 0.01
weights = weights - learning_rate * dw
print(weights)

[[0.37079012]
 [0.94071431]]


In [36]:
for n_iters in range(1000):
  m = num_samples
  y_pred_train = np.dot(X_train, weights)
  y_pred_train = sigmoid(y_pred_train)
  dw = (1/num_samples) * np.dot(X_train.T, (y_pred_train - y_train))
  weights = weights - learning_rate * dw

print(weights)

[[-0.01454432]
 [ 0.0032288 ]]


In [38]:
def predict(X):
    y_pred = np.dot(X, weights)
    y_pred = sigmoid(y_pred)
    y_pred = np.where(y_pred >= 0.5, 1, 0)
    return y_pred

y_pred = predict(X_test)
print(y_pred)
print(y_test)

[[1]
 [0]]
   Target
8       1
1       0


In [43]:
class LogisticRegression1:
  def __init__(self, num_features):
    self.lr = 0.01
    self.np_iter = 1000
    self.weights = np.random.rand(num_features, 1)

  def fit(self, X_train, y_train):
    num_samples, num_features = X_train.shape
    y_train_np = y_train.values
    for i in range(self.np_iter):
      y_pred = np.dot(X_train, self.weights)
      y_pred = self.sigmoid(y_pred)
      dw = (1/num_samples) * np.dot(X_train.T, (y_pred - y_train_np))
      self.weights = self.weights - self.lr * dw

  def predict(self , X):
    y_pred = np.dot(X, self.weights)
    y_pred = self.sigmoid(y_pred)
    y_pred = np.where(y_pred >= 0.5, 1, 0)
    return y_pred

  def sigmoid(self, z):
    z = np.exp(-z)
    z = np.add(1, z)
    z = np.divide(1, z)
    z = np.where(z >= 0.5, 1, 0)
    return z

clf1 = LogisticRegression1(num_features=2)
clf1.fit(X_train, y_train)
y_pred = clf1.predict(X_test)
print(y_pred)
print(y_test)

[[1]
 [0]]
   Target
8       1
1       0


In [44]:
from sklearn.linear_model import LogisticRegression

clf3 = LogisticRegression()
clf3.fit(X_train, y_train)
y_pred = clf3.predict(X_test)
print(y_pred)
print(y_test)

[1 0]
   Target
8       1
1       0


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
