In [130]:
#row -> Samples
#X axis -> features
#Y axis -> labels

In [131]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

y = np.array([3, 4, 5, 6, 7, 8, 9, 10, 11, 12])


In [132]:
print(X.reshape(-1,1))

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [133]:
bias_column = np.ones((X.shape[0], 1))
X_with_bias = np.hstack((bias_column, X.reshape(-1, 1)))
print(X_with_bias)

[[ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 1.  8.]
 [ 1.  9.]
 [ 1. 10.]]


In [134]:
X_df = pd.DataFrame(X_with_bias, columns=['Bias', 'Features'])
print(X_df)

   Bias  Features
0   1.0       1.0
1   1.0       2.0
2   1.0       3.0
3   1.0       4.0
4   1.0       5.0
5   1.0       6.0
6   1.0       7.0
7   1.0       8.0
8   1.0       9.0
9   1.0      10.0


In [135]:
y_df = pd.DataFrame(y, columns=['Target'])
print(y_df)

   Target
0       3
1       4
2       5
3       6
4       7
5       8
6       9
7      10
8      11
9      12


In [136]:
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size=0.2, random_state=42)

print("X_train:")
print(X_train)
print("\ny_train:")
print(y_train)
print("\nX_test:")
print(X_test)
print("\ny_test:")
print(y_test)

X_train:
   Bias  Features
5   1.0       6.0
0   1.0       1.0
7   1.0       8.0
2   1.0       3.0
9   1.0      10.0
4   1.0       5.0
3   1.0       4.0
6   1.0       7.0

y_train:
   Target
5       8
0       3
7      10
2       5
9      12
4       7
3       6
6       9

X_test:
   Bias  Features
8   1.0       9.0
1   1.0       2.0

y_test:
   Target
8      11
1       4


In [137]:
#Step - 3

num_samples, num_features = X_train.shape
print("Number of samples:", num_samples)
print("Number of features:", num_features)

Number of samples: 8
Number of features: 2


In [138]:
weights = np.random.rand(num_features, 1)
print("Initial weights:", weights)
print("Shape of the matrix:", weights.shape)

Initial weights: [[0.49927252]
 [0.07878994]]
Shape of the matrix: (2, 1)


In [139]:
#step - 4

y_pred = np.dot(X_train, weights)
print("Predicted values:", y_pred)

Predicted values: [[0.97201218]
 [0.57806246]
 [1.12959207]
 [0.73564235]
 [1.28717196]
 [0.89322224]
 [0.81443229]
 [1.05080212]]


In [140]:
#step - 5

m = num_samples
dw = (1/m) * np.dot(X_train.T, (y_pred - y_train))
print (dw)

[[ -6.56738279]
 [-42.79937826]]


In [141]:
#step - 6

lr = 0.01
weights = weights - lr * dw
print("Updated weights:", weights)

Updated weights: [[0.56494634]
 [0.50678373]]


In [142]:
#step - 7

for i in range (1000):
    y_pred = np.dot(X_train, weights)
    dw = (1/m) * np.dot(X_train.T, (y_pred - y_train))
    weights = weights - lr * dw

print("Final weights:", weights)

Final weights: [[1.79941134]
 [1.02956889]]


In [143]:
#Step - 8

def predict(X, weights):
    y_pred1 = np.dot(X_test, weights)
    return y_pred1

y_pred1 = predict(X_test, weights)
print("Predicted values:", y_pred1)
print("Test Values:", y_test)

Predicted values: [[11.06553133]
 [ 3.85854911]]
Test Values:    Target
8      11
1       4


In [147]:
#step - 9

class CustomLinearRegression:
  def __init__(self, learning_rate=0.01, n_iters = 15000, weights = None):
    self.learning_rate = learning_rate
    self.n_iters = n_iters
    self.weights = weights

  def fit(self, X, y):
    num_samples, num_features = X.shape
    y_np = y.values
    for i in range(self.n_iters):
      y_pred = np.dot(X, self.weights)
      dw = (1/num_samples) * np.dot(X.T, (y_pred - y_np))
      self.weights = self.weights - self.learning_rate * dw

  def predict(self , X):
    y_pred = np.dot(X, self.weights)
    return y_pred

In [148]:
clf = CustomLinearRegression(weights=np.random.rand(num_features, 1))
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print("Predicted values:", y_pred)

Predicted values: [[11.]
 [ 4.]]


In [149]:
from sklearn.linear_model import LinearRegression

clf1 = LinearRegression()
clf1.fit(X_train, y_train)
y_pred3 = clf1.predict(X_test)
print("Predicted values:", y_pred3)
print()
print("Test Values:", y_test)

Predicted values: [[11.]
 [ 4.]]

Test Values:    Target
8      11
1       4
