In [ ]:
import numpy as np

x = np.array([[3,7],
             [1,8],
             [4,5],
             [2,6]])

y = np.array([1,0,1,0])
best_gain = float ("inf")
split_index = None
split_thresholds = None

In [ ]:
class Node:
    def __init__(self, feature=None, threshold=None, left=None, right=None, value=None):
      self.feature = feature
      self.threshold = threshold
      self.left = left
      self.right = right
      self.value = value

    def is_leaf(self):
      if self.value is not None:
        return True
      else:
        return False

In [ ]:
def Most_Common_Label(y):
      labels, counts = np.unique(y, return_counts=True)
      index = np.argmax(counts)
      return labels[index]

print (Most_Common_Label(y))

0


In [ ]:
def Split(X_column, split_threshold):
  left_indices = np.argwhere(X_column <= split_threshold).flatten()
  right_indices = np.argwhere(X_column > split_threshold).flatten()
  return left_indices, right_indices

In [ ]:
def Entropy(y):
  fID3 = np.mean(y)
  if fID3 == 0 or fID3 == 1:
    return 0
  else:
    return -fID3 * np.log(fID3) - (1 - fID3) * np.log(1 - fID3)

print (Entropy(y))

0.6931471805599453


In [ ]:
def Information_Gain(y, X_column, split_threshold):
  left_indices, right_indices = Split(X_column, split_threshold)
  if len(left_indices) == 0 or len(right_indices) == 0:
    return 0
  e_left = Entropy(y[left_indices])
  e_right = Entropy(y[right_indices])
  nl = len(left_indices)
  nr = len(right_indices)
  n = len(y)
  weighted_entropy = (nl / n) * e_left + (nr / n) * e_right
  return weighted_entropy
print (Information_Gain(y, x[:,0], 4))

0


In [ ]:
def Best_Split(best_gain, split_index, split_threshold): # Changed split_thresholds to split_threshold
  X_column = x[:, 0]
  X_column_sorted = np.sort(X_column)
  thresholds = (X_column_sorted[:-1] + X_column_sorted[1:])/2
  for threshold in thresholds:
    gain = Information_Gain(y, X_column, threshold) # Changed thresholds to threshold
    if gain < best_gain:
      best_gain = gain
      split_index = 0
      split_threshold = threshold # Changed split_thresholds to split_threshold

In [ ]:
def build_tree(X, y):
  n_labels = len(np.unique (y))

  if (n_labels == 1):
    leaf_value = Most_Common_Label(y)
    return Node(value=leaf_value)

  best_feature, best_threshold = Best_Split(X, y) # Fixed typo: best_thresold to best_threshold
  left_indices, right_indices = Split(X[:, best_feature], best_threshold)
  left_subtree = build_tree(X[left_indices, :], y[left_indices])
  right_subtree = build_tree(X[right_indices, :], y[right_indices])
  return Node(best_feature, best_threshold, left_subtree, right_subtree)

In [ ]:
def traverse_tree(x, node):
  if node.is_leaf():
    return node

  if x[node.feature] <= node.threshold:
    return traverse_tree(x, node.left)
  else:
    return traverse_tree(x, node.right)

In [ ]:
def predict(X):
  predictions = []
  for x in X:
    prediction = traverse_tree(x, root)
    predictions.append(prediction)
  return np.array(predictions)

In [ ]:
import numpy as np

class DecisionTree:
  class Node:
      def __init__(self, feature=None, threshold=None, left=None, right=None, value=None):
        self.feature = feature
        self.threshold = threshold
        self.left = left
        self.right = right
        self.value = value

      def is_leaf(self):
        if self.value is not None:
          return True
        else:
          return False

  def __init__(self):
    self.root = None
    self.best_gain = float("inf")
    self.split_index = None
    self.split_threshold = None
    self.best_feature = None
    self.best_threshold = None

  def fit(self, X, y):
    self.root = self.build_tree(X, y)

  def Most_Common_Label(self, y):
      labels, counts = np.unique(y, return_counts=True)
      index = np.argmax(counts)
      return labels[index]

  def Split(self, X_column, split_threshold):
    left_indices = np.argwhere(X_column <= split_threshold).flatten()
    right_indices = np.argwhere(X_column > split_threshold).flatten()
    return left_indices, right_indices

  def Entropy(self, y):
    fID3 = np.mean(y)
    if fID3 == 0 or fID3 == 1:
      return 0
    else:
      return -fID3 * np.log(fID3) - (1 - fID3) * np.log(1 - fID3)

  def Information_Gain(self, y, X_column, split_threshold):
    left_indices, right_indices = self.Split(X_column, split_threshold)
    if len(left_indices) == 0 or len(right_indices) == 0:
      return 0
    e_left = self.Entropy(y[left_indices])
    e_right = self.Entropy(y[right_indices])
    nl = len(left_indices)
    nr = len(right_indices)
    n = len(y)
    weighted_entropy = (nl / n) * e_left + (nr / n) * e_right
    return weighted_entropy

  def Best_Split(self, X, y):
    best_gain = float("inf")
    split_index = None
    split_threshold = None

    for feature_index in range(X.shape[1]):
      X_column = X[:, feature_index]
      X_column_sorted = np.sort(X_column)
      thresholds = (X_column_sorted[:-1] + X_column_sorted[1:])/2
      for threshold in thresholds:
        gain = self.Information_Gain(y, X_column, threshold)
        if gain < best_gain:
          best_gain = gain
          split_index = feature_index
          split_threshold = threshold
    return split_index, split_threshold


  def build_tree(self, X, y):
    n_labels = len(np.unique (y))

    if (n_labels == 1):
      leaf_value = self.Most_Common_Label(y)
      return self.Node(value=leaf_value)

    best_feature, best_threshold = self.Best_Split(X, y)

    if best_feature is None:
        leaf_value = self.Most_Common_Label(y)
        return self.Node(value=leaf_value)

    left_indices, right_indices = self.Split(X[:, best_feature], best_threshold)

    if len(left_indices) == 0 or len(right_indices) == 0:
        leaf_value = self.Most_Common_Label(y)
        return self.Node(value=leaf_value)


    left_subtree = self.build_tree(X[left_indices, :], y[left_indices])
    right_subtree = self.build_tree(X[right_indices, :], y[right_indices])
    return self.Node(best_feature, best_threshold, left_subtree, right_subtree)


  def traverse_tree(self, x, node):
    if node.is_leaf():
      return node

    if x[node.feature] <= node.threshold:
      return self.traverse_tree(x, node.left)
    else:
      return self.traverse_tree(x, node.right)

  def predict(self, X):
    predictions = []
    for x_row in X:
      predicted_node = self.traverse_tree(x_row, self.root)
      predictions.append(predicted_node.value)
    return np.array(predictions)


classifier = DecisionTree()
classifier.fit(x, y)
predictions = classifier.predict(x)
print(predictions)
print (y)

[1 0 1 0]
[1 0 1 0]


In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf.fit(x,y)
predictions = clf.predict(x)
print(predictions)

[1 0 1 0]
