In [58]:
#Steps to PCA

#1.Centering the values aka
    #mean of both features
    #subtract the mean form the features to get the targets
#2. Calculating the covariance Matrix
    #calculating the eigen values
#4. Calculate the eigen vectors
#5. Calculate the principal components

In [59]:
import numpy as np

X = np.array([[126, 78],
              [128, 80],
              [128, 82],
              [130, 82],
              [130, 84],
              [132, 86]])

In [60]:
class PCAnumpy:
  def __init__(self, n_components = 1, mean = None):
    self.n_components = n_components
    self.mean = mean

  def fit_transform(self, X):
    self.mean = np.mean(X, axis = 0)
    X_centered = X - self.mean
    cov = np.cov(X_centered.T, ddof = 1)
    eigenvalues, eigenvectors = np.linalg.eig(cov)
    indices = np.argsort(eigenvalues)[::-1]
    sorted_eigenvalues = eigenvalues[indices]
    sorted_eigenvectors = eigenvectors[:, indices]
    for i in range(sorted_eigenvectors.shape[1]):
      max_abs_idx = np.argmax(np.abs(sorted_eigenvectors[:, i]))
      if sorted_eigenvectors[max_abs_idx, i] < 0:
        sorted_eigenvectors[:, i] *= -1

    new_data = np.dot(X_centered, sorted_eigenvectors)
    return new_data[:, :self.n_components]

In [61]:
model = PCAnumpy()
y_pred = model.fit_transform(X)
print(y_pred)



[[-4.99953747]
 [-2.20523715]
 [-0.58906316]
 [ 0.58906316]
 [ 2.20523715]
 [ 4.99953747]]


In [62]:
from sklearn.decomposition import PCA
pca = PCA()
y_pred = pca.fit_transform(X)
print(y_pred)

[[-4.99953747 -0.06800833]
 [-2.20523715  0.37003933]
 [-0.58906316 -0.80808699]
 [ 0.58906316  0.80808699]
 [ 2.20523715 -0.37003933]
 [ 4.99953747  0.06800833]]


In [63]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('banknote_authentication.csv', sep = ',')

X = df[['variance', 'skewness']]

standardScaler = StandardScaler()
X_scaled = standardScaler.fit_transform(X)

model = PCAnumpy()
y_pred1 = model.fit_transform(X_scaled)
print(y_pred1)

[[ 1.6060239 ]
 [ 1.77591184]
 [ 0.30437946]
 ...
 [-2.89489698]
 [-2.2366944 ]
 [-1.05142821]]


In [64]:
from sklearn.decomposition import PCA
pca = PCA()
y_pred2 = pca.fit_transform(X_scaled)
print(y_pred2)


[[ 1.6060239  -0.01955113]
 [ 1.77591184  0.27054807]
 [ 0.30437946  1.40372141]
 ...
 [-2.89489698  0.81267   ]
 [-2.2366944   0.24733077]
 [-1.05142821 -0.42942643]]
