In [11]:
import numpy as np

X = np.array(([2, 3], [1, 1], [2, 1], [4, 5], [5, 4], [6, 6]))

y = np.array((-1, -1, -1, 1, 1, 1))

In [12]:
class SVMNumpy:
  def __init__(self, learning_rate=0.01, C=0.001, n_iters=1000):
    self.learning_rate = learning_rate
    self.C = C
    self.n_iters = n_iters
    self.w = None
    self.b = None

  def fit(self, X, y):
    n_rows, n_columns = X.shape
    y_ = np.where(y <= 0, -1, 1)
    self.w = np.zeros(n_columns)
    self.b = 0
    for i in range(self.n_iters):
      for idx, x_i in enumerate(X):
        condition = y_[idx] * (np.dot(x_i, self.w) - self.b) >= 1
        if condition:
          self.w -= self.learning_rate * (2 * self.C * self.w)
        else:
          self.w -= self.learning_rate * (2 * self.C * self.w - np.dot(x_i, y_[idx]))
          self.b -= self.learning_rate * y_[idx]

  def predict(self, X):
    prediction = np.dot(X, self.w) - self.b
    return np.sign(prediction)

In [13]:
model = SVMNumpy()
model.fit(X, y)
y_pred = model.predict(X)
print(y_pred)

accuracy = np.sum(y_pred == y) / len(y)
print(accuracy)


[-1. -1. -1.  1.  1.  1.]
1.0


In [14]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

clf = SVC(kernel='linear')
clf.fit(X, y)
y_pred = clf.predict(X)
print(y_pred)

accuracy_score = accuracy_score(y, y_pred)
print(accuracy_score)

[-1 -1 -1  1  1  1]
1.0


In [15]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
import numpy as np
from sklearn.model_selection import train_test_split

df = pd.read_csv('winequality-total.csv', sep=';')

X = df.drop('quality', axis = 1).values
y_raw = df['quality'].values

y = np.where(y_raw <= 4, -1, 1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

class SVMNumpy1:
  def __init__(self, learning_rate=0.01, C=0.001, n_iters=1000):
    self.learning_rate = learning_rate
    self.C = C
    self.n_iters = n_iters
    self.w = None
    self.b = None

  def fit(self, X, y):
    n_rows, n_columns = X.shape
    #y_ = np.where(y <= 0, -1, 1)
    y_ = y
    self.w = np.zeros(n_columns)
    self.b = 0
    for i in range(self.n_iters):
      for idx, x_i in enumerate(X):
        condition = y_[idx] * (np.dot(x_i, self.w) - self.b) >= 1
        if condition:
          self.w -= self.learning_rate * (2 * self.C * self.w)
        else:
          self.w -= self.learning_rate * (2 * self.C * self.w - np.dot(x_i, y_[idx]))
          self.b -= self.learning_rate * y_[idx]

  def predict(self, X):
    prediction = np.dot(X, self.w) - self.b
    return np.sign(prediction).astype(int)

clf2 = SVMNumpy1()
clf2.fit(X_train_scaled, y_train)
y_pred = clf2.predict(X_test_scaled)
print(y_pred)

def accuracy(y_test, y_pred):
  accuracy = np.mean(y_test == y_pred)
  return accuracy
print(f"Accuracy is: {accuracy(y_test, y_pred) * 100:.2f}%")

[1 1 1 ... 1 1 1]
Accuracy is: 96.31%


In [16]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

clf3 = SVC(kernel='linear')
clf3.fit(X_train_scaled, y_train)
y_pred = clf3.predict(X_test_scaled)
print(y_pred)

print(f"Accuracy is: {accuracy_score(y_test, y_pred) * 100:.2f}%")

[1 1 1 ... 1 1 1]
Accuracy is: 96.31%
